dataset: 
  root: 'data/'
  dataset_name: 'japanese_food'
  class_name: ['ramen', 'sashimi', 'sushi','takoyaki']
  
model: 
  name: 'mobilenet'
  variant : 'v3-large' 
  width_multi: 1.0  

train:
  epochs: 10
  batch_size: 8
  num_worker: 4
  lr: 0.001
  model_path: 'mobilenetv3L_food.pt'
  pretrained_path: 'pretrained_weights/mobilenetv3-large.pt'
  save_dir: 'experiments'
  
test:
  model_path: 'experiments/mobilenetv3-large_202211030833/mobilenetv3L_food.pt'