dataset: 
  root: 'data/'
  dataset_name: 'japanese_food'
  class_name: ['ramen', 'sashimi', 'sushi','takoyaki']
  
model: 
  name: 'convnext'
  variant : 'tiny' 
  width_multi: 1.0  

train:
  epochs: 10
  batch_size: 8
  num_worker: 4
  optimizer: 'adamw'
  lr: 0.00005
  model_path: 'convnext_food.pt'
  pretrained_path: 'pretrained_weights/convnexttiny.pt'
  save_dir: 'experiments'
  
test:
  model_path: 'experiments/convnexttiny_202211101600/convnext_food.pt'